[launcher]
background                = "#170C08"
background-alpha          = 0.97
text                      = "#F0D8C1"
border                    = "hyprland.active-border"
border-alpha              = 1.0
scrim                     = "#050302"
scrim-alpha               = 0.66
selected-background       = "#F07818"
selected-background-alpha = 0.22
selected-text             = "#FFF0DF"
selected-border           = "#F07818"
selected-border-alpha     = 0.90
